### ISSUE TITLE
[Meteor 1.8.3, 1.10-rc.11] fails with QUALIA_PROFILE_FOLDER set

### ISSUE THREAD

**Issue by hexsprite** [qualialabs/profile#11]
I get a similar traceback on both versions of Meteor, presumably something to do with the monkey patching involved.

1.8.3:

```
/Users/jbb/co/focuster/.meteor/local/build/programs/server/mini-files.js:1
(function (exports, require, module, __filename, __dirname) { module.export({
                                                                           ^

TypeError: module.export is not a function
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/mini-files.js:1:76)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/npm-require.js:10:15)
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/npm-require.js:194:3)
```

1.10-rc.11:

```
/Users/jbb/co/focuster/.meteor/local/build/programs/server/mini-files.js:1
module.export({
             ^

TypeError: module.export is not a function
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/mini-files.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/npm-require.js:10:15)
    at Object.<anonymous> (/Users/jbb/co/focuster/.meteor/local/build/programs/server/npm-require.js:194:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

**Comment by Pagebakers** [comment]
Did you find a solution in meanwhile?

**Comment by hexsprite** [comment]
I think a new version was released but I haven't tried it yet

**Comment by sagar947** [comment]
Did you find a solution? I'm facing the same issue on Meteor v1.10.1.

**Comment by Pagebakers** [comment]
it seems to be related to an outdated meteor package, but unclear which one

**Comment by sagar947** [comment]
@hexsprite were you able to solve this issue? If so, can you direct me with the steps?
