### ISSUE TITLE
Qualia profiler breaks application

### ISSUE THREAD

**Issue by lucaciraolo** [qualialabs/profile#12]
When I run my project using `meteor` it works fine but when I try and run it with the QUALIA_PROFILE_FOLDER environment variable set, my build breaks. I'd love some help as I'm trying to investigate incredibly long reload times.

Using meteor 1.10.2, node v14.5.0 on Windows

```
=> Started proxy.
Profiling "initial-build"gins                |
=> Started MongoDB.
W20200702-17:11:22.846(2)? (STDERR) C:\Users\lucac\Documents\GitHub\AMRE-AmDex\app\.meteor\local\build\programs\server\mini-files.js:1
W20200702-17:11:22.896(2)? (STDERR) module.export({
W20200702-17:11:22.897(2)? (STDERR)              ^
W20200702-17:11:22.903(2)? (STDERR) 
W20200702-17:11:22.903(2)? (STDERR) TypeError: module.export is not a function
W20200702-17:11:22.904(2)? (STDERR)     at Object.<anonymous> (C:\Users\lucac\Documents\GitHub\AMRE-AmDex\app\.meteor\local\build\programs\server\mini-files.js:1:14)
W20200702-17:11:22.907(2)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1158:30)
W20200702-17:11:22.908(2)? (STDERR)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
W20200702-17:11:22.911(2)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:1002:32)
W20200702-17:11:22.912(2)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
W20200702-17:11:22.913(2)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1044:19)
W20200702-17:11:22.913(2)? (STDERR)     at require (internal/modules/cjs/helpers.js:77:18)
W20200702-17:11:22.914(2)? (STDERR)     at Object.<anonymous> (C:\Users\lucac\Documents\GitHub\AMRE-AmDex\app\.meteor\local\build\programs\server\npm-require.js:10:15)
W20200702-17:11:22.915(2)? (STDERR)     at Object.<anonymous> (C:\Users\lucac\Documents\GitHub\AMRE-AmDex\app\.meteor\local\build\programs\server\npm-require.js:194:3)
W20200702-17:11:22.922(2)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1158:30)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by djlogan2** [comment]
No comment since the original July 2 post? I have the same issue.

**Comment by andrewtackett** [comment]
I also have the same issue

**Comment by veered** [comment]
This package has been forked and has support for newer versions of Meteor: https://github.com/quavedev/profile
